version: '3.7'

services:
  database:
    container_name: database
    image: postgres:12-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: express-database
      PGDATA: /data/postgres
    volumes:
      - ./src/databases/resources:/var/lib/data/resources
      - ./src/databases/resources/file-dev.sql:/docker-entrypoint-initdb.d/file-dev.sql
      - ./src/databases/resources/file-prod.sql:/docker-entrypoint-initdb.d/file-prod.sql
    ports:
      - 5432:5432
    restart: always
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready']
      interval: 10s
      timeout: 5s
      retries: 5

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4:latest
    environment:
      PGADMIN_DEFAULT_EMAIL: zxc@gmail.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - 5050:80
    restart: always

  server:
    build:
      context: ./
      dockerfile: Dockerfile
    image: server
    container_name: server
    depends_on:
      database:
        condition: service_healthy
    ports:
      - 4000:4000
    env_file:
      - .env.production
    volumes:
      - ./logs:/logs

networks:
  default:
    name: express-network

volumes:
  postgres_data:
    driver: local
